import { useMemo, useState } from 'react';
import { ArrowRight, BriefcaseBusiness, Check, ChevronRight, CircleHelp, FileText, Handshake, LayoutDashboard, Link2, Loader2, Plus, Search, Sparkles, Target, Upload, X } from 'lucide-react';
import { supabase } from './supabase';

type View = 'home' | 'onboarding' | 'dashboard' | 'jobs' | 'studio' | 'share';
type Job = { company: string; title: string; location: string; comp: string; score: number; stage: string; next: string; accent: string };

const demoJobs: Job[] = [
  { company: 'OpenAI', title: 'Product Marketing Lead, Consumer Subscriptions', location: 'San Francisco · Hybrid', comp: '$284K–$315K + equity', score: 9.8, stage: 'Targeting', next: 'Find a warm path before applying', accent: 'violet' },
  { company: 'Snap', title: 'Head of User Growth Strategy & Operations', location: 'Los Angeles · Hybrid', comp: '$251K–$377K', score: 9.5, stage: 'Ready to apply', next: 'Review tailored application pack', accent: 'yellow' },
  { company: 'OpenAI', title: 'Growth — Lifecycle Lead', location: 'SF or NYC', comp: '$239K–$325K + equity', score: 9.2, stage: 'Intro requested', next: 'Follow up with warm contact', accent: 'violet' },
  { company: 'Crunchyroll', title: 'Head of eCommerce', location: 'Los Angeles · Hybrid', comp: '$260K–$305K', score: 8.6, stage: 'Saved', next: 'Research team and P&L scope', accent: 'blue' },
];

const nav = [
  ['Today', 'dashboard', LayoutDashboard], ['My jobs', 'jobs', BriefcaseBusiness], ['Career Passport', 'onboarding', FileText], ['AI Studio', 'studio', Sparkles], ['Share & support', 'share', Handshake]
] as const;

function App() {
  const [view, setView] = useState<View>('home');
  const [authOpen, setAuthOpen] = useState(false);
  const [email, setEmail] = useState('');
  const [sent, setSent] = useState(false);
  const [jobModal, setJobModal] = useState(false);
  const [jobUrl, setJobUrl] = useState('');
  const [jobs, setJobs] = useState(demoJobs);
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState('');

  const ask = () => {
    if (!question.trim()) return;
    setAnswer(`Here’s a strong starting point based on your Career Passport:\n\n• Lead with the most relevant, measurable result—not a generic responsibility.\n• Mirror the role’s language, but keep every fact grounded in your verified experience.\n• For this next step, I’d prioritize a warm introduction and a tailored one-page narrative.\n\nOnce your account is connected, FastBilly will use your actual résumé, achievements, and saved roles to make this specific.`);
  };

  const signIn = async () => {
    if (!email) return;
    if (supabase) {
      // Career is mounted at /career on fastbilly.com. Route the magic-link
      // callback back into the subapp instead of the marketing homepage.
      const redirectTo = `${window.location.origin}/career/auth/callback`;
      await supabase.auth.signInWithOtp({ email, options: { emailRedirectTo: redirectTo } });
    }
    setSent(true);
  };

  const addJob = () => {
    if (!jobUrl.trim()) return;
    setJobs([{ company: 'New opportunity', title: 'Job saved for review', location: 'Add location', comp: 'Comp not yet analyzed', score: 0, stage: 'Saved', next: 'Paste the job description in AI Studio', accent: 'blue' }, ...jobs]);
    setJobUrl(''); setJobModal(false); setView('jobs');
  };

  const stats = useMemo(() => ({ actions: 4, live: jobs.length, warm: 3, profile: 72 }), [jobs]);

  return <div className="app-shell">
    {view !== 'home' && <aside className="sidebar">
      <button className="brand sidebar-brand" onClick={() => setView('home')}><span className="brand-dot">✦</span><span>fastbilly</span><em>career</em></button>
      <div className="nav-list">{nav.map(([label, key, Icon]) => <button key={key} className={`nav-item ${view === key ? 'active' : ''}`} onClick={() => setView(key as View)}><Icon size={18}/><span>{label}</span>{key === 'dashboard' && <b>4</b>}</button>)}</div>
      <div className="sidebar-bottom"><div className="profile-pill"><div className="avatar">BH</div><div><strong>Bill Hudak</strong><span>Career in motion</span></div><ChevronRight size={16}/></div></div>
    </aside>}

    <main className={view === 'home' ? 'main home-main' : 'main'}>
      {view === 'home' && <Home onStart={() => setView('onboarding')} onAuth={() => setAuthOpen(true)} />}
      {view === 'onboarding' && <Onboarding onDone={() => setView('dashboard')} onAuth={() => setAuthOpen(true)} />}
      {view === 'dashboard' && <Dashboard stats={stats} jobs={jobs} onJobs={() => setView('jobs')} onStudio={() => setView('studio')} onShare={() => setView('share')} />}
      {view === 'jobs' && <Jobs jobs={jobs} onAdd={() => setJobModal(true)} onStudio={() => setView('studio')} />}
      {view === 'studio' && <Studio question={question} setQuestion={setQuestion} answer={answer} ask={ask} />}
      {view === 'share' && <Share onAuth={() => setAuthOpen(true)} />}
    </main>

    {authOpen && <AuthModal email={email} setEmail={setEmail} sent={sent} onSubmit={signIn} onClose={() => { setAuthOpen(false); setSent(false); }} />}
    {jobModal && <JobModal value={jobUrl} setValue={setJobUrl} onSave={addJob} onClose={() => setJobModal(false)} />}
  </div>;
}

function Home({ onStart, onAuth }: { onStart: () => void; onAuth: () => void }) {
  return <><header className="home-header"><button className="brand" onClick={() => window.scrollTo({top:0,behavior:'smooth'})}><span className="brand-dot">✦</span><span>fastbilly</span><em>career</em></button><nav><a href="#how">How it works</a><a href="#features">What it does</a><button className="text-btn" onClick={onAuth}>Sign in</button><button className="small-cta" onClick={onStart}>Start your search <ArrowRight size={15}/></button></nav></header>
  <section className="hero"><div className="eyebrow">YOUR CAREER, ORGANIZED</div><h1>Build your career once.<br/><i>Move it forward</i> every day.</h1><p>FastBilly turns your résumé, goals, experience, and network into a private job-search command center—with an AI sidekick that knows your story.</p><div className="hero-actions"><button className="primary-cta" onClick={onStart}>Build my Career Passport <ArrowRight size={18}/></button><button className="watch-link" onClick={() => document.getElementById('how')?.scrollIntoView({behavior:'smooth'})}>See how it works <span>↓</span></button></div><div className="hero-proof"><span><Check size={14}/> Private by default</span><span><Check size={14}/> No invented résumé facts</span><span><Check size={14}/> Built for real momentum</span></div></section>
  <section className="hero-card"><div className="card-topline"><span>YOUR SEARCH · TODAY</span><span className="live-dot">● LIVE</span></div><div className="today-grid"><div className="focus-panel"><p>GOOD AFTERNOON, BILL</p><h2>Four moves.<br/><i>One direction.</i></h2><button onClick={onStart}>Open your day <ArrowRight size={16}/></button></div><div className="action-stack"><Action n="01" label="Finish your Career Passport" meta="72% complete"/><Action n="02" label="Ask Sarah for the OpenAI intro" meta="High-impact · today"/><Action n="03" label="Review Snap application pack" meta="Ready to submit"/></div></div></section>
  <section id="how" className="how"><div className="section-kicker">THE LOOP</div><h2>Less searching. More <i>moving.</i></h2><div className="step-grid"><Step n="01" title="Build your Passport" body="Bring your résumé, LinkedIn, wins, credentials, and the life you’ve already built." icon={<FileText/>}/><Step n="02" title="Choose your direction" body="Tell us what great looks like: roles, places, compensation, industries, and dealbreakers." icon={<Target/>}/><Step n="03" title="Make the move" body="Turn a job link into a tailored plan, strong materials, the right ask, and a next step." icon={<ArrowRight/>}/></div></section>
  <section id="features" className="feature-band"><div><span className="eyebrow">NOT ANOTHER JOB BOARD</span><h2>Everything you need to make a better case for <i>yourself.</i></h2></div><div className="feature-list"><Feature title="Career Passport" text="Your professional life, structured once and ready whenever opportunity shows up."/><Feature title="Application Studio" text="Tailored resumes, cover letters, answers, and prep—grounded in facts you approve."/><Feature title="Warm path finder" text="Make a clear ask, package the right context, and keep every follow-up from falling through."/><Feature title="Progress you can share" text="Give a mentor or friend the smallest, safest slice of your search they need to help."/></div></section>
  <footer><span>© 2026 FastBilly</span><span>Career in motion.</span></footer></>;
}
const Action = ({n,label,meta}:{n:string;label:string;meta:string}) => <div className="action-row"><span>{n}</span><div><strong>{label}</strong><small>{meta}</small></div><ChevronRight size={17}/></div>;
const Step = ({n,title,body,icon}:{n:string;title:string;body:string;icon:React.ReactNode}) => <article className="step"><div className="step-head"><span>{n}</span>{icon}</div><h3>{title}</h3><p>{body}</p></article>;
const Feature = ({title,text}:{title:string;text:string}) => <div className="feature"><span>✦</span><div><h3>{title}</h3><p>{text}</p></div></div>;

function Onboarding({ onDone, onAuth }: { onDone: () => void; onAuth: () => void }) {
 const [step,setStep]=useState(1); const [name,setName]=useState('');
 return <div className="onboarding"><div className="onboard-header"><button className="brand" onClick={() => history.back()}><span className="brand-dot">✦</span><span>fastbilly</span><em>career</em></button><span>STEP {step} OF 4</span><button className="save-exit" onClick={onAuth}>Save & sign in</button></div><div className="progress"><i style={{width:`${step*25}%`}}/></div><section className="onboard-body">{step===1 && <><span className="eyebrow">LET’S START WITH YOU</span><h1>Your career is more<br/>than a <i>résumé.</i></h1><p>We’ll use it as a starting point, then help you fill in the work you’re proud of and the direction you want next.</p><div className="upload-box"><Upload size={23}/><strong>Drop in your résumé</strong><span>PDF or DOCX · we’ll never change your facts</span><button>Choose file</button></div><div className="or"><span/>or<span/></div><input className="big-input" value={name} onChange={e=>setName(e.target.value)} placeholder="Start by telling us your name"/><button className="primary-cta" onClick={()=>setStep(2)}>Keep going <ArrowRight size={18}/></button></>}{step===2 && <><span className="eyebrow">YOUR WORK, YOUR WORDS</span><h1>What kind of work<br/>are you <i>after?</i></h1><p>Choose a few starting points. You can change these any time.</p><div className="chip-grid">{['Growth & marketing','Product','Engineering','Design','Operations','Sales','Finance','People','Creative','Healthcare','Education','Other'].map(x=><button key={x} className="choice-chip">{x}</button>)}</div><button className="primary-cta" onClick={()=>setStep(3)}>Keep going <ArrowRight size={18}/></button></>}{step===3 && <><span className="eyebrow">SET THE DIRECTION</span><h1>What would make the<br/>next move <i>right?</i></h1><p>We use this to rank opportunities—not to box you in.</p><div className="form-grid"><label>Target titles<input placeholder="e.g. Head of Growth, Product Lead"/></label><label>Where can you work?<input placeholder="e.g. Los Angeles, remote"/></label><label>Work style<select><option>Choose one or more</option><option>Remote</option><option>Hybrid</option><option>On-site</option></select></label><label>Compensation target<input placeholder="e.g. $180,000+"/></label></div><button className="primary-cta" onClick={()=>setStep(4)}>Keep going <ArrowRight size={18}/></button></>}{step===4 && <><span className="eyebrow">YOUR FIRST DAY</span><h1>Good. You’ve got<br/>a place to <i>start.</i></h1><p>FastBilly will turn this into your personal search space. Add what you know now; improve it as you move.</p><div className="ready-card"><Sparkles/><div><strong>Career Passport ready to build</strong><span>We’ll keep your facts private and your next steps clear.</span></div></div><button className="primary-cta" onClick={onDone}>Open my command center <ArrowRight size={18}/></button></>}</section></div>;
}

function Dashboard({stats,jobs,onJobs,onStudio,onShare}:{stats:{actions:number;live:number;warm:number;profile:number};jobs:Job[];onJobs:()=>void;onStudio:()=>void;onShare:()=>void}) { return <div className="workspace"><header className="workspace-header"><div><span className="eyebrow">TUESDAY · SEPTEMBER 8</span><h1>Good afternoon, <i>Bill.</i></h1></div><button className="small-cta" onClick={onJobs}><Plus size={16}/> Save a job</button></header><section className="momentum"><div className="momentum-copy"><span>YOUR SEARCH IS IN MOTION</span><h2>{stats.actions} moves worth making<br/><i>today.</i></h2><p>Start with the work that changes the odds—not the work that just feels busy.</p></div><div className="momentum-metrics"><Metric value={`${stats.profile}%`} label="Passport built"/><Metric value={String(stats.live)} label="Live opportunities"/><Metric value={String(stats.warm)} label="Warm paths"/></div></section><section className="two-col"><div><div className="section-line"><h2>Today’s moves</h2><button onClick={onJobs}>See all <ArrowRight size={15}/></button></div><div className="moves"><Move tag="HIGH IMPACT" title="Ask Sarah for the OpenAI introduction" detail="Product Marketing Lead, Consumer Subscriptions · 9.8 fit" button="Prepare ask"/><Move tag="READY" title="Review your Snap application package" detail="Head of User Growth Strategy & Operations · 9.5 fit" button="Review"/><Move tag="FOLLOW UP" title="Check in with your lifecycle-growth contact" detail="OpenAI Growth — Lifecycle Lead · intro requested" button="Draft follow-up"/></div></div><aside className="side-card"><div className="side-card-top"><span>ASK FASTBILLY</span><Sparkles size={18}/></div><h3>Need a thought partner?</h3><p>Use your full career context to make the next thing easier.</p><button onClick={onStudio}>Open AI Studio <ArrowRight size={15}/></button><div className="share-mini"><Handshake size={17}/><div><strong>Don’t go it alone.</strong><span>Share a focused packet with someone who can help.</span></div><button onClick={onShare}>Share</button></div></aside></section><section><div className="section-line"><h2>Priority opportunities</h2><button onClick={onJobs}>View pipeline <ArrowRight size={15}/></button></div><div className="job-grid">{jobs.slice(0,3).map((j,i)=><JobCard key={i} job={j}/>)}</div></section></div> }
const Metric=({value,label}:{value:string;label:string})=><div className="metric"><strong>{value}</strong><span>{label}</span></div>;
const Move=({tag,title,detail,button}:{tag:string;title:string;detail:string;button:string})=><div className="move"><div className="move-tag">{tag}</div><div className="move-copy"><strong>{title}</strong><span>{detail}</span></div><button>{button}<ArrowRight size={14}/></button></div>;
const JobCard=({job}:{job:Job})=><article className="job-card"><div className="job-card-head"><div className={`company-mark ${job.accent}`}>{job.company[0]}</div><span className="score">{job.score ? `${job.score} FIT` : 'NEW'}</span></div><h3>{job.title}</h3><p>{job.company} · {job.location}</p><div className="job-card-foot"><span>{job.stage}</span><ChevronRight size={17}/></div></article>;

function Jobs({jobs,onAdd,onStudio}:{jobs:Job[];onAdd:()=>void;onStudio:()=>void}) { return <div className="workspace"><header className="workspace-header"><div><span className="eyebrow">OPPORTUNITY PIPELINE</span><h1>Make the right moves,<br/><i>not all the moves.</i></h1></div><button className="small-cta" onClick={onAdd}><Plus size={16}/> Save a job</button></header><div className="pipeline-summary"><span>{jobs.length} opportunities</span><span>·</span><span>3 warm paths</span><span>·</span><span>2 ready to apply</span><button onClick={onStudio}><Sparkles size={15}/> Analyze a role</button></div><div className="job-list">{jobs.map((j,i)=><div key={i} className="job-list-row"><div className={`company-mark ${j.accent}`}>{j.company[0]}</div><div className="job-main"><strong>{j.title}</strong><span>{j.company} · {j.location}</span></div><div className="job-comp">{j.comp}</div><div className="fit-pill">{j.score ? `${j.score} FIT` : 'TO REVIEW'}</div><div className="stage-pill">{j.stage}</div><button className="arrow-button"><ChevronRight size={19}/></button><div className="job-next">NEXT · {j.next}</div></div>)}</div><div className="empty-cta"><Link2 size={20}/><div><strong>Found something interesting?</strong><span>Paste the job link. We’ll turn it into a plan.</span></div><button onClick={onAdd}>Save a job <ArrowRight size={15}/></button></div></div> }

function Studio({question,setQuestion,answer,ask}:{question:string;setQuestion:(v:string)=>void;answer:string;ask:()=>void}) { const starters=['Make my résumé stronger for this job','Draft a warm referral request','What should I emphasize in my story?','Prep me for a recruiter screen']; return <div className="studio"><header className="workspace-header"><div><span className="eyebrow">AI STUDIO</span><h1>Your career.<br/><i>In context.</i></h1></div><span className="grounded"><Check size={14}/> Grounded in your approved facts</span></header><div className="studio-orb">✦</div><h2>What do you want to move forward?</h2><p>Ask about a role, your résumé, outreach, interview prep, or the next smartest thing to do.</p><div className="prompt-box"><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="e.g. Help me make a strong case for this role…"/><button onClick={ask}><ArrowRight size={19}/></button></div><div className="starter-chips">{starters.map(s=><button key={s} onClick={()=>setQuestion(s)}>{s}</button>)}</div>{answer && <article className="ai-answer"><div><Sparkles size={17}/><span>FASTBILLY</span></div><p>{answer}</p><small>Demo guidance until your private career facts and AI provider are connected.</small></article>}</div> }

function Share({onAuth}:{onAuth:()=>void}) { return <div className="workspace share"><header className="workspace-header"><div><span className="eyebrow">SUPPORT SYSTEM</span><h1>Getting hired is<br/>a team <i>sport.</i></h1></div></header><p className="lead">Give someone the smallest, clearest piece of your search they need to help—without handing over your whole private world.</p><div className="share-grid"><article><div className="share-icon"><Handshake/></div><span>ROLE PACKET</span><h2>Ask for one specific thing.</h2><p>Share a job, a selected résumé, why you fit, and a clear ask for a referral or introduction.</p><button onClick={onAuth}>Create a role packet <ArrowRight size={15}/></button></article><article><div className="share-icon coral"><FileText/></div><span>CAREER PACKET</span><h2>Bring a supporter into the loop.</h2><p>Give a mentor or friend a carefully chosen view of your direction, progress, and where you need help.</p><button onClick={onAuth}>Create a career packet <ArrowRight size={15}/></button></article><article className="invite-card"><span>INVITE A FRIEND</span><h2>Know someone in motion?</h2><p>Give them their own private place to build a better job search.</p><div className="invite-link">fastbilly.com/career/invite/you <button onClick={() => navigator.clipboard?.writeText('fastbilly.com/career/invite/you')}>Copy</button></div></article></div><div className="privacy-note"><CircleHelp size={18}/><div><strong>Your career remains yours.</strong><span>Every share is private, scoped, revocable, and never public by default.</span></div></div></div> }

function AuthModal({email,setEmail,sent,onSubmit,onClose}:{email:string;setEmail:(v:string)=>void;sent:boolean;onSubmit:()=>void;onClose:()=>void}) { return <div className="modal-backdrop"><div className="modal"><button className="close" onClick={onClose}><X size={19}/></button><span className="brand-dot big">✦</span>{sent ? <><h2>Check your inbox.</h2><p>We sent a secure sign-in link to <strong>{email}</strong>. Open it here to continue.</p></> : <><span className="eyebrow">WELCOME IN</span><h2>Your next move starts here.</h2><p>Sign in or create your private FastBilly Career workspace.</p><button className="google-btn" onClick={()=>alert('Google sign-in will be enabled when the OAuth provider is configured in Supabase.')}>Continue with Google</button><div className="or"><span/>or<span/></div><label>Email address<input autoFocus value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" type="email"/></label><button className="primary-cta full" onClick={onSubmit}>{supabase ? 'Send magic link' : 'Continue with email'} <ArrowRight size={17}/></button><small>{supabase ? 'We’ll email you a secure sign-in link.' : 'Authentication is being connected—this UI is ready.'}</small></>}</div></div> }
function JobModal({value,setValue,onSave,onClose}:{value:string;setValue:(v:string)=>void;onSave:()=>void;onClose:()=>void}) { return <div className="modal-backdrop"><div className="modal job-modal"><button className="close" onClick={onClose}><X size={19}/></button><span className="eyebrow">SAVE AN OPPORTUNITY</span><h2>Found a possible next move?</h2><p>Drop in the job URL now. FastBilly will help turn it into an application plan.</p><label>Job URL<input autoFocus value={value} onChange={e=>setValue(e.target.value)} placeholder="https://company.com/careers/job…"/></label><div className="or"><span/>or<span/></div><button className="paste-desc" onClick={()=>{setValue('Job description ready to paste');}}>Paste a job description instead</button><button className="primary-cta full" onClick={onSave}>Save opportunity <ArrowRight size={17}/></button></div></div> }
export default App;
